baseURL = 'https://neroil.github.io/MVP_CommissionPlatform/'
languageCode = 'en-us'
title = 'MVP Commission Platform'
theme = 'spectral'
defaultContentLanguage = "en"
#googleAnalytics = "G-XXXXXXXXXX"

[params]
fancyTitle = "Hello, World!"  # Frontpage Title
copyright = "MVP Art Commission Platform"
description = 'Welcome to the MVP Art Commission platform. Created using Hugo and the Spectral theme.'
#startbuttonText = "Activate"
#startbuttonLink = "#"
body_is_markdown = true
#custom_css = "foo.css"
#custom_sass = "bar.scss"
#images = ["path_to_social_image_for_link_previews.jpg"]

[pagination]
pagerSize = 7  # New format for pagination


[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/posts/'
title = "Posts"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Welcome to MVP Art Commission!'
body = 'This is a "Hello, World!" page created with Hugo and the Spectral theme.'

[[params.one.icon]]
icon = "fa-smile"
style = "1"
label = "Welcome"

[params.cta]
enable = true
title = "Ready to commission your next artwork?"
body = "Join us and explore the platform!"

[[params.cta.link]]
href = "#"
text = "Learn More"
special = false

[params.contact]
enable = true
title = "Contact"
body = "Leave us a message."
phone = "+49 (0) 030 000 000"
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "nospam@example.com"
subject = "New Submission!"
formspree_form_id = "example_invalid"

[params.social]
twitter = ""
mastodon = ""
github = ""
facebook = ""
youtube = ""
instagram = ""
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"

[languages.es]
weight = 10
languageName = "Español"
